### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by probonopd** [kleinesfilmroellchen/serenity-imager#2]
Hello, the link https://klfr.spdns.de/serenity-iso mentioned in the README.md is broken.

It would be really nice if there was a way to download SerenityOS ISOs without having to build them.

**Comment by kleinesfilmroellchen** [comment]
I stopped running this system around this January and took down the site shortly after, due to size restrictions and the fact that the distributed image wasn't enough to boot Serenity (you also need the Kernel and Prekernel images). However, you're right in that I should remove the link from the README.
